### PR TITLE
Create change_ssid_when_servers_not_accessible

### PR DESCRIPTION
**Pull request by smoe**
Hello,
This is something close to my heart and I somehow felt that your current list of projects lack something that is more straight-forward and easy, nonetheless tremendously helpful IMHO.

### Checklist for new or updates project ideas

- [x] I added at least one contact option so interested people can get in touch with me.
- [x] Data for my project is valid

### CODE REVIEW

**Comment by andibraeu** [comment]
Hi @smoe 

do you have anyone else in mind for mentoring?

**Comment by smoe** [comment]
> do you have anyone else in mind for mentoring?
Sadly, I feel somewhat remote to Gluon development these days/years and would thus prefer to have someone closer to the inner circles to adopt this project. This would then (very likely) a) be a better mentor and b) help introducing the student to a larger set of Freifunk folks.

**Comment by T-X** [comment]
@smoe I think that already exists? https://github.com/freifunk-gluon/community-packages/tree/master/ffac-ssid-changer

**Comment by smoe** [comment]
This seems like done, indeed. So, what would be required adopt that remote branch for the gluon main distribution? Maybe we could win the author of that work ( @maurerle ?) as a mentor?

**Comment by maurerle** [comment]
There would be little benefit of having this in gluon upstream repository vs the community-packages, I think.
The ssid changer currently works by changing the config and doing a `killall -HUP hostapd` while it would be better to have a ubus call for hostapd to only change the current SSID of the Wifi.
I think there is still an issue with OWE transition mode if the SSID to transition to does not exist (because it was changed)

And it would be better to have it written in Lua instead of this Shell script :)

And yes, I could mentor someone on this if needed.

**Pull request merged**
